version: '3'

services:

  caddy:
    image: abiosoft/caddy:php-no-stats
    volumes:
      - ./docker/caddy/Caddyfile:/etc/Caddyfile
      - .:/usr/src/app
    ports:
      - 8001:2015
    links:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    working_dir: /usr/src/app/public
    volumes:
      - .:/usr/src/app

  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    env_file:
      - .env
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    command: 'npm run watch'

  db:
    image: postgres:11
    env_file:
      - .db.env
    volumes:
      - devict-jobs-pgdata:/var/lib/postgresql/data

  # This service is just used for running artisan commands
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    working_dir: /usr/src/app
    env_file:
      - .env
    volumes:
      - .:/usr/src/app

volumes:
  devict-jobs-pgdata:
